version: "3"

services:
  web:
    build: .
    expose:
      - "8000"
    env_file:
      - docker.env
    depends_on:
      - db
    networks:
      - moonhive_network


  db:
    image: postgres:latest
    env_file:
      - docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - moonhive_network

networks:
  moonhive_network:

volumes:
  postgres_data:
